# -*- coding: utf-8 -*-
"""AnnivPmiiDev.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-aljx_P04bOtSub4ZKZVX4AdCCjBUnI5
"""

import calendar
year = 2022
month = 10
anniv = "23 October 2022 \nHappy 1st Anniversary pmiidev"

print(calendar.month(year,month))
print(anniv)

import datetime as dt

tanggal = int(input("Tanggal \t: "))
bulan = int(input("Bulan \t\t: "))
tahun = int(input("Tahun \t\t: "))

tgl_lahir = dt.date(tahun,bulan,tanggal)
print(f"PMIIDEV berdiri : {tgl_lahir}")

hari_ini = dt.date.today()
print(f"Hari ini tanggal: {hari_ini}")

umur_hari = hari_ini - tgl_lahir
umur_tahun = umur_hari.days // 365
umur_bulan_sisa = (umur_hari.days % 365) // 30

print(f"Hari nya adalah : {tgl_lahir:%A}")
print(f"Umur PMIIDEV : {umur_tahun} tahun, {umur_bulan_sisa} bulan")